// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/file/collect/": {
            "post": {
                "description": "收藏文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "收藏文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件id与收藏夹id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.collecttmp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"收藏成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"} or {\"message\":\"参数不全，请输入collectlist_id\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"文件未找到！“} or {\"message\":\"收藏行为不能被记录！“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/delete/": {
            "delete": {
                "description": "删除文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tmpfileid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"删除成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"} or{\"message\":\"身份认证错误！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"未找到或删除出现错误！“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/download/": {
            "get": {
                "description": "下载文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tmpfileid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"删除成功！\", \"file_url\":fileid对应的fileurl}",
                        "schema": {
                            "$ref": "#/definitions/model.Downloadfile"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"文件未找到！“} or {\"message\":\"下载行为不能被记录！“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/fileinfo/:fileid/": {
            "get": {
                "description": "获取文件具体信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "获取文件具体信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "传入除了数类的数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.File"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"信息获取成功\",\"file\":file结构体的所有信息}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"请输入fileid\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"查无此项或查询失败！\"} or {\"message\":\"该文件的上传时间查询出现问题\"} ",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/like/": {
            "post": {
                "description": "点赞文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "点赞文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tmpfileid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"点赞成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"} or {\"message\":\"该用户已点过赞\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"点赞行为无法被记录！“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/score/": {
            "post": {
                "description": "评分",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "评分",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件id与本次打分分数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.tmpscore"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"评分成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"} or {\"message\":\"评分失败！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"评分统计失败“} or {\"message\":\"未找到相应文件“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/searching/latest/": {
            "get": {
                "description": "获取最新发布的若干数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "根据上传时间查询文件",
                "parameters": [
                    {
                        "description": "规定的数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.tmp"
                        }
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页所显示的数据",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"信息获取成功\",\"files\":在检索条件下的file切片的所有信息}",
                        "schema": {
                            "$ref": "#/definitions/model.Getfiles"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"} or {\"message\":\"数据获取失败\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/searching/popular/": {
            "get": {
                "description": "获取热门下载内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "根据下载数查询文件",
                "parameters": [
                    {
                        "description": "规定的数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.tmp"
                        }
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "一页所显示的数据",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"信息获取成功\",\"files\":在检索条件下的file切片的所有信息}",
                        "schema": {
                            "$ref": "#/definitions/model.Getfiles"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"} or {\"message\":\"数据获取失败\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/unfavorite/": {
            "delete": {
                "description": "取消收藏",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "取消收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件id与收藏夹id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.collecttmp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"取消收藏成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "403": {
                        "description": "{\"message\":\"收藏统计失败\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"未找到或取消收藏失败！“} or {\"message\":\"找不到对应文件“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/unlike/": {
            "delete": {
                "description": "取消点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "文件",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Tmpfileid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"取消点赞成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"取消点赞行为无法被记录！“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/upload/": {
            "post": {
                "description": "上传文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "传入文件相关数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.File"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"上传成功\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"建立数据失败“} or {\"message\":\"上传行为无法被记录“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/file/uploadbyOss/:fileid/": {
            "post": {
                "consumes": [
                    "multipart/form-data",
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "上传文件,返回url，文件储存在oss上，同时得到一个可访问的地址，实质上实现了上传与下载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "fileid",
                        "name": "fileid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "资料文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"删除成功！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"查无此项或查询失败!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"生成地址失败“} or{\"message\":\"上传文件未生成一个可供匹配的地址，已删除，上传不成功\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/message/": {
            "get": {
                "description": "传入hostid与pagesize，page获取数组数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "获取用户留言板信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "留言板主人的id",
                        "name": "hostid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码内容大小，即显示数量",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"操作成功\",\"message_list\":数组,返回一系列留言属性}",
                        "schema": {
                            "$ref": "#/definitions/model.Getmessage"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"传入参数不全\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"未能成功找到相应留言内容\"} or {\"message\":\"未能成功获取留言用户头像信息！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/message/leave/": {
            "post": {
                "description": "根据userid检测是否为已注册用户进行的操作，随后根据传入的信息进行留言记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "发出留言",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "留言的对象以及留言内容",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Note"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"留言成功!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"无留言内容，请输入留言内容\"} or {\"message\":\"留言失败！\"} ",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/collect_list/": {
            "put": {
                "description": "收藏夹重命名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collectlist"
                ],
                "summary": "收藏夹改名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "收藏夹id与新收藏夹名字",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.data"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"收藏夹改名成功\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"未找到收藏夹“} or {\"message\":\"数据更新失败“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/collect_list/create/": {
            "post": {
                "description": "新建收藏夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collectlist"
                ],
                "summary": "新建收藏夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "收藏夹名称",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.tmpstring"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"收藏夹建立成功\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"收藏夹建立失败“} ",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/collect_list/delete/": {
            "delete": {
                "description": "删除收藏夹",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collectlist"
                ],
                "summary": "删除收藏夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user的认证令牌",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "收藏夹id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.tmpint"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"收藏夹删除成功\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Res"
                        }
                    },
                    "400": {
                        "description": "{\"message\":\"Bad Request!\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "401": {
                        "description": "{\"message\":\"身份认证错误，请先登录或注册！\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "404": {
                        "description": "{\"message\":\"收藏夹删除失败“}",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.collecttmp": {
            "type": "object",
            "properties": {
                "collectlist_id": {
                    "type": "integer"
                },
                "file_id": {
                    "type": "integer"
                }
            }
        },
        "handler.data": {
            "type": "object",
            "properties": {
                "collectlist_id": {
                    "type": "integer"
                },
                "collectlist_name": {
                    "type": "string"
                }
            }
        },
        "handler.tmp": {
            "type": "object",
            "properties": {
                "college": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.tmpint": {
            "type": "object",
            "properties": {
                "collectlist_id": {
                    "type": "integer"
                }
            }
        },
        "handler.tmpscore": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "handler.tmpstring": {
            "type": "object",
            "properties": {
                "collectlist_name": {
                    "type": "string"
                }
            }
        },
        "model.Downloadfile": {
            "type": "object",
            "properties": {
                "file_url": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.File": {
            "type": "object",
            "properties": {
                "college": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "file_title": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.Getfiles": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.File"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Getmessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "message_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Messagelist"
                    }
                }
            }
        },
        "model.Messagelist": {
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "write_time": {
                    "type": "string"
                },
                "writer_id": {
                    "type": "string"
                }
            }
        },
        "model.Note": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Res": {
            "type": "object",
            "properties": {
                "massage": {
                    "type": "string"
                }
            }
        },
        "model.Tmpfileid": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "47.102.120.167:2333",
	BasePath:    "/sharing/v1/",
	Schemes:     []string{},
	Title:       "sharing",
	Description: "资料共享平台",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
